name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Adjust this as needed

jobs:
  run-tests:
    runs-on: ubuntu-latest  # Underlying runner, but we'll run everything inside an Alpine container

    container:
      image: docker:dind  # Use Docker-in-Docker
      options: --privileged  # Necessary for Docker-in-Docker to work

    steps:
      # Step 1: Install required dependencies in Alpine container
      - name: Set up Alpine environment
        run: |
          apk update
          apk add --no-cache make docker-compose bash py3-pip python3-virtualenv
          python3 -m venv venv
          . venv/bin/activate
          pip install -r tests/requirements.txt

      # Step 2: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Run the makefile command to spin up services and run tests
      - name: Run tests for go-gorilla service
        run: make test-service go-gorilla
